src/WDT_Assignment_2/Models/Movie.cs
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace WDT_Assignment_2.Models
{
    public partial class Movie
    {
        public Movie()
        {
            CineplexMovie = new HashSet<CineplexMovie>();
        }

        public int MovieId { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string ImageUrl { get; set; }
        public decimal Price { get; set; }

        [JsonIgnore]
        public virtual ICollection<CineplexMovie> CineplexMovie { get; set; }
    }
}

src/WDT_Assignment_2/Controllers/CinemasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WDT_Assignment_2.Models;
using MoreLinq;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace WDT_Assignment_2.Controllers
{
    public class CinemasController : Controller
    {
        private MovieCineplexContext _db;
        private CineplexMovieManager cineplexMM = CineplexMovieManager.Instance;

        public CinemasController(MovieCineplexContext db)
        {
            _db = db;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult GetAllCinemas()
        {
            ViewData["AllCinemas"] = _db.Cineplex.ToList<Cineplex>();
            
            return View("AllCinemas");
        }

        public IActionResult GetMoviesByCinema(int id)
        {
            List<Movie> movies = new List<Movie>(cineplexMM.GetMoviesByCinemaId(id));
            var filteredCinepelx = movies.DistinctBy(x => x.MovieId).ToList();
            ViewData["MoviesByCinema"] = filteredCinepelx;

            return View("MoviesByCinema");
        }

        public IActionResult SearchCinemas(string search)
        {
            List<Cineplex> searchedCinemas = new List<Cineplex>();

            if (!String.IsNullOrEmpty(search))
            {
                searchedCinemas = _db.Cineplex.Where(m => m.Location.Contains(search)).ToList<Cineplex>();

                ViewData["AllCinemas"] = searchedCinemas;
            }
            else
            {
                ViewData["AllCinemas"] = _db.Movie.ToList();
            }

            return View("AllCinemas");
        }

        public IActionResult CinemaFirst(int cinemaId, int movieId)
        {
            Cineplex cineplex = (Cineplex)cineplexMM.GetCinemaById(cinemaId);
            Movie movie = (Movie)cineplexMM.GetMovieById(movieId);
            List<Session> sessions = cineplexMM.GetSessionsByCinemaIdAndMovieId(cinemaId, movieId);

            // Does not deserialize properly
            //{
            //    {cineplex, movie}
            //};
            //HttpContext.Session.Set("CurrentCinemaMovie", currentCinemaMovie);
            //HttpContext.Session.Set("CurrentCinemaMovie", currentCinemaMovie);
            HttpContext.Session.Set("CurrentCineplex", cineplex);
            HttpContext.Session.Set("CurrentMovie", movie);

            Dictionary<Movie, List<Session>> dict = new Dictionary<Movie, List<Session>>
            {
                {movie, sessions}
            };

            ViewData["CinemaFirst"] = dict;

            return View("CinemaFirst");
        }
    }
}

src/WDT_Assignment_2/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WDT_Assignment_2.Models;
using System.Data.SqlClient;
using System.Data;
using MoreLinq;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace WDT_Assignment_2.Controllers
{
    public class MoviesController : Controller
    {
        private MovieCineplexContext _db;

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public MoviesController(
            MovieCineplexContext db,
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager)
        {
            _db = db;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            // Cheeky login session checker
            if(!HttpContext.Session.IsExists("LoggedIn") && _signInManager.IsSignedIn(User))
            {
                return RedirectToAction("SessionLogOff", "Account");
            }

            ViewData["AllMovies"] = _db.Movie.ToList<Movie>();

            return View();
        }

        public IActionResult UpcomingMovies()
        {
            ViewData["AllUpcoming"] = _db.MovieComingSoon.ToList();

            return View();
        }

        //invoke using localhost/movies/id
        public IActionResult MovieFirst(int id)
        {

            CineplexMovie cineplexMovie = _db.CineplexMovie.FirstOrDefault(p => p.MovieId == id);
            List<Cineplex> cineplex = _db.CineplexMovie.Where(p => p.MovieId == id).Select(c => c.Cineplex).ToList();
            var filteredCinepelx = cineplex.DistinctBy(x => x.CineplexId).ToList();
            Movie movie = _db.CineplexMovie.Where(p => p.MovieId == id).Select(m => m.Movie).FirstOrDefault();

            Dictionary<CineplexMovie, List<Cineplex>> dict = new Dictionary<CineplexMovie, List<Cineplex>>
            {
                {cineplexMovie, filteredCinepelx }
            };

            ViewData["MovieFirst"] = dict;
            return View("MovieFirst");
        }

        //invoke using link localhost/movies/all
        public IActionResult GetAllMovies()
        {
            List<Movie> movieList = _db.Movie.ToList<Movie>();
            var filteredMovieList = movieList.DistinctBy(x => x.MovieId).ToList();
            ViewData["Movies"] = filteredMovieList;
            return View("Movies");
        }

        public IActionResult SearchMovies(string search)
        {
            List<Movie> searchedMovies = new List<Movie>();

            if (!String.IsNullOrEmpty(search))
            {
                searchedMovies = _db.Movie.Where(m => m.Title.Contains(search)).ToList<Movie>();

                ViewData["Movies"] = searchedMovies;
            }
            else
            {
                ViewData["Movies"] = _db.Movie.ToList();
            }

            return View("Movies");
        }
    }
}

src/WDT_Assignment_2/Views/Movies/Index.cshtml
@using WDT_Assignment_2.Models;
@{
    ViewData["Title"] = "Home";

    var allMovies = (List<Movie>)ViewData["AllMovies"];
}

<h2>Welcome to ABC Cineplex</h2>
<br />
<p>ABC Cineplex has many luxury class <a asp-controller="Cinemas" asp-action="GetAllCinemas">Movie Plaza theatres</a> across Melbourne.</p>

<br />
<hr />

<h2 class="text-center">Now Showing</h2>

<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner" role="listbox">
        @{
            foreach (var movie in allMovies)
            {
                string activeString = movie.MovieId == 1 ? "item active" : "item";
                <div class="@activeString">
                    <a asp-area="" asp-controller="Movies" asp-action="MovieFirst" asp-route-id="@movie.MovieId">
                        <img src="@Url.Content(movie.ImageUrl)" alt="Test slide" class="img-responsive" style="margin:auto; width:100%;" />
                        @*<div class="carousel-caption" style="padding-top:10px">
                            <h3>@movie.Title</h3>
                        </div>*@
                    </a>
                </div>
            }
        }
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
</div>

src/WDT_Assignment_2/Views/Movies/MovieFirst.cshtml
@using WDT_Assignment_2.Models;

@{
    ViewData["Title"] = "MovieFirst";
    var dict = (Dictionary<CineplexMovie, List<Cineplex>>)ViewData["MovieFirst"];
    var cineplexMovie = dict.ElementAt(0).Key;
    var allCinemas = dict.ElementAt(0).Value;
}


<div class="container">
    @if (ViewData["MovieFirst"] == null)

    {
        <p>Sorry, Movie not found</p>
    }
    else
    {
        <div class="row" style="margin-top:50px">

            <div class="col-md-4">
                <div class="thumbnail">
                    <div class="caption">
                        <h3>@cineplexMovie.Movie.Title</h3>
                    </div>

                    <img src="@Url.Content(cineplexMovie.Movie.ImageUrl)" alt="@cineplexMovie.Movie.Title" style="width:100%; height:520px;" />
                </div>
            </div>

            <div class="col-md-6">
                <div class="thumbnail">
                    <div class="caption">
                        <h3>Choose Theatre Location</h3>
                    </div>
                    @foreach (var cinema in allCinemas)
                    {
                        <ul>
                            <li>
                                <a asp-area="" asp-controller="Cinemas" asp-action="CinemaFirst" asp-route-cinemaId="@cinema.CineplexId" asp-route-movieId="@cineplexMovie.Movie.MovieId">
                                    <h4>@cinema.Location</h4>
                                </a>
                            </li>
                        </ul>
                    }

                </div>

                <div class="thumbnail">
                    <div class="caption">
                        <h3>About</h3>
                    </div>
                    <p>@cineplexMovie.Movie.LongDescription</p>
                </div>
            </div>

        </div>
    }
</div>

src/WDT_Assignment_2/Views/Movies/Movies.cshtml
@using WDT_Assignment_2.Models;

@{
    ViewData["Title"] = "Movies";
    var allMovies = (List<Movie>)ViewData["Movies"];
}

<br /><br />

<ul class="nav nav-tabs">
    <li class="active"><a href="#">Now Showing</a></li>
    <li><a asp-area="" asp-controller="Movies" asp-action="UpcomingMovies">Upcoming</a></li>
</ul>

<br /><br />

@*
    https://www.w3schools.com/bootstrap/bootstrap_images.asp
*@
<div class="container">

    <div style="margin-bottom:10px">

        <form method="get" asp-controller="Movies" asp-action="SearchMovies">
            <label for="search">Search movies</label>
            <input type="text" name="search" id="search" />
            <button type="submit" class="btn btn-md">Search</button>
        </form>
    </div>

    <div class="row">
        @{
            foreach (var movie in allMovies)
            {
                <div class="col-md-4">
                    <div class="thumbnail">
                        <a asp-area="" asp-controller="Movies" asp-action="MovieFirst" asp-route-id="@movie.MovieId">
                            <img src="@Url.Content(movie.ImageUrl)" alt="@movie.Title" style="width:100%; height:520px;" />
                            <div class="caption">
                                <h3>@movie.Title</h3>
                                <p>@movie.ShortDescription</p>
                            </div>
                        </a>
                    </div>
                </div>
            }
        }
    </div>
</div>

src/WDT_Assignment_2/Views/Movies/UpcomingMovies.cshtml
@using WDT_Assignment_2.Models;

@{
    ViewData["Title"] = "Upcoming Movies";
    var allUpcoming = (List<MovieComingSoon>)ViewData["AllUpcoming"];
}

<br /><br />

<ul class="nav nav-tabs">
    <li><a asp-area="" asp-controller="Movies" asp-action="GetAllMovies">Now Showing</a></li>
    <li class="active"><a href="#">Upcoming</a></li>
</ul>

<br /><br />

@*
    https://www.w3schools.com/bootstrap/bootstrap_images.asp
*@
<div class="container">
    <div class="row">
        @{
            foreach (var movie in allUpcoming)
            {
                <div class="col-md-4">
                    <div class="thumbnail">
                        <a asp-area="" asp-controller="Movies" asp-action="@movie.MovieComingSoonId">
                            <img src="@Url.Content(movie.ImageUrl)" alt="@movie.Title" style="width:100%; height: 520px" />
                            <div class="caption">
                                <h3>@movie.Title</h3>
                                <p>@movie.ShortDescription</p>
                            </div>
                        </a>
                    </div>
                </div>
            }
        }
    </div>
</div>